### PR TITLE
ci: Travis -> GitHub Actions

### PR DESCRIPTION
**Pull request by odscjames**

### CODE REVIEW

**Comment by odscjames** [comment]
[Switch from Travis to GitHub Actions](https://trello.com/c/sLVHLfoo/46-switch-from-travis-to-github-actions)

**Comment by odscjames** [comment]
Whoever approves this will need to go into Repository Settings, Protected Branch, and change the "Require status checks to pass before merging " option - tick the new CI ones, untick Travis, then merge!

**Review by michaelwood — COMMENTED** [review]
I think it would be good to split out the lint into a separate one, that seems more like the GH way and may be slightly faster as it can happen in parallel with the pytests you can also drop unnecessary python version from the lint as there isn't a need to lint for all versions I wouldn't have thought? 
e.g. https://github.com/OpenDataServices/lib-cove/pull/69/commits/2564b6414b2df5a0cb2b8b5c6dce07af96429b5d

Would also be nice to have some white space to make the file more readable.

**Comment by odscjames** [comment]
> may be slightly faster

Given additional time to spin up and install I would [Reference needed] that but the point about the Python versions and general separation is good - will do that.

> Would also be nice to have some white space to make the file more readable.

I'm not sure what you're looking for here and as we haven't talked about this at all I'll leave this for now. Personally it looks ok to me, and my way of making it more readable is "more comments" :-) Separating out the linting will actually remove the need for some of the complex stuff anyway.

**Review by Bjwebb — APPROVED** [review]

**Pull request merged**
