### PR TITLE
Some typos

### PR DESCRIPTION
**Pull request by fchapoton**
and a few minor code details in the 3rd commit

### CODE REVIEW

**Comment by odscjames** [comment]
Thank you! Can I ask how you decided we don't need to catch `IOError` - was there some tool that was used to detect this?

**Comment by jpmckinney** [comment]
In Python 3.3+, IOError is an alias of OSError https://docs.python.org/3/library/exceptions.html#OSError.filename2 https://peps.python.org/pep-3151/#confusing-set-of-os-related-exceptions

**Comment by fchapoton** [comment]
I am using the tool `ruff`, which can check many things.

Here : https://docs.astral.sh/ruff/rules/os-error-alias/

**Comment by odscjames** [comment]
Thank you! Merged in.

**Pull request closed without merging**
