### PR TITLE
ODSReader: Fix parsing date and number formatting from .ods files 

### PR DESCRIPTION
**Pull request by BibianaC**
Was not converting correctly.
relates to #342

### CODE REVIEW

**Comment by Bjwebb** [comment]
This makes a change for all date values, which might cause problems for IATI. I can check this later in the week.

**Comment by Bjwebb** [comment]
I've pushed an `.ods` and an `.xlsx` to this branch, which demonstrate the differences for xml output:

```
$ flatten-tool unflatten flattentool/tests/fixtures/xlsx/dates.xlsx -f xlsx --xml
<?xml version='1.0' encoding='utf-8'?>
<iati-activities>
  <!--XML generated by flatten-tool-->
  <main>
    <some-date>2020-12-01</some-date>
    <some-datetime>2020-12-01T00:00:00+00:00</some-datetime>
    <without-the-d-word>2020-12-01</without-the-d-word>
  </main>
</iati-activities>

$ flatten-tool unflatten flattentool/tests/fixtures/ods/dates.ods -f ods --xml
<?xml version='1.0' encoding='utf-8'?>
<iati-activities>
  <!--XML generated by flatten-tool-->
  <main>
    <some-date>2020-12-01T00:00:00Z</some-date>
    <some-datetime>2020-12-01T00:00:00Z</some-datetime>
    <without-the-d-word>2020-12-01T00:00:00Z</without-the-d-word>
  </main>
</iati-activities>
```

This relevant code on this expects a datetime object, which the xlsx provides, rather than a string. I think the best thing to do is to parse the string to a datetime object in the bit of code you've been looking at.

**Comment by Bjwebb** [comment]
[Getting .ods working](https://trello.com/c/PGkLdIHu/14-getting-ods-working)

**Comment by Bjwebb** [comment]
Here's some dev deploys of this:
IATI: http://flattentool-342-last-modified-does-not-convert.cove.cove-dev-2.default.opendataservices.uk0.bigv.io/
360Giving: http://flattentool-342-last-modified-does-not-convert.cove-360-dev.default.threesixtygiving.uk0.bigv.io/

**Review by kindly — APPROVED** [review]

**Pull request merged**
