### PR TITLE
json_input: If `json_dict` is not a dict, return a useful error/warning

### PR DESCRIPTION
**Pull request by Bjwebb**
https://github.com/OpenDataServices/flatten-tool/issues/442

### CODE REVIEW

**Comment by Bjwebb** [comment]
@jpmckinney Does this look like what you were expecting?

**Comment by jpmckinney** [comment]
Yes, looks good!

**Review by R2ZER0 — APPROVED** [review]
Looks good to me :+1:

**Comment by Bjwebb** [comment]
I will make a release tomorrow.

**Pull request merged**
