### PR TITLE
First go at a change log

### PR DESCRIPTION
**Pull request by odscjames**

### CODE REVIEW

**Comment by odscjames** [comment]
This is a first go at a changelog - as I wasn't involved in the release there may be bits missing, or there may be better ways to write stuff. If so, please correct. ("Do not hardcode iati-activities for top level for all xml" should maybe be in Added, for instance?)

**Comment by andylolz** [comment]
I think “require lxml” removes an undocumented feature (as per #198). So I’d consider that a bugfix :)

But I’m mostly just saying that because I reported the bug, so it means the changelog has even more andylolz in it 🤣

**Comment by odscjames** [comment]
Maybe it's both? It might be a bugfix. But also, the fact there is now a new explicit requirement is probably also worth mentioning in some way? It might trip people up, so good to warn people.

Happy to give credit when due and add even more andylolz in :-)

**Comment by andylolz** [comment]
> Maybe it's both? It might be a bugfix. But also, the fact there is now a new explicit requirement is probably also worth mentioning in some way? It might trip people up, so good to warn people.

Good point; agreed!

**Comment by odscjames** [comment]
If you have suggested edits, feel free to push to this branch (if allowed?) or comment here and I'll add them for you?

**Comment by odscjames** [comment]
(I don't fully understand some of the issues but I can try and look soon and write something better!)

**Pull request merged**
