### PR TITLE
use-titles: Use $ref'erring title if available

### PR DESCRIPTION
**Pull request by jpmckinney**
Presently, in OCDS, tender/value and tender/minValue get converted to the same title, because they are at the same level in the hierarchy and refer to the same `Value` object. (Same for all the period objects.)

To fix this, the "title" property in the referring schema (not in the referred definition) ought to be used.

cc @yolile

### CODE REVIEW

**Comment by jpmckinney** [comment]
@yolile Please use this branch, because `--use-titles` is broken in Flatten Tool until this is fixed.

**Comment by jpmckinney** [comment]
@yolile Also, I don't know if anyone else is publishing CSV using Spanish headings, but once this is merged and released, they will need to update Flatten Tool (and we might want to do that in our shared notebooks).

**Comment by yolile** [comment]
> @yolile Also, I don't know if anyone else is publishing CSV using Spanish headings, but once this is merged and released, they will need to update Flatten Tool (and we might want to do that in our shared notebooks).

No, that I'm aware of. Honduras, Paraguay, and Buenos Aires are using the "path" headings

**Comment by odscjames** [comment]
I needed to rebase this (we have just switched C.I.) and add a changelog entry - I can't change this pull request so I made a new one at https://github.com/OpenDataServices/flatten-tool/pull/369 . Before putting that up for review, I want to look for a really simple data example to make into a test so we can avoid regressing this behaviour - I'll see if I can find something. I'll leave this pull request open for now, for reference.

**Comment by odscjames** [comment]
@jpmckinney  I've added a test case at https://github.com/OpenDataServices/flatten-tool/pull/369 if you could check?

**Comment by jpmckinney** [comment]
Looks good, thanks!

I'll close this PR.

**Pull request closed without merging**
