### PR TITLE
Generate reference tables

### PR DESCRIPTION
**Pull request by jpmckinney**
Opening PR for branch mentioned in #101 so that it's better surfaced.

### CODE REVIEW

**Comment by jpmckinney** [comment]
Tagging @Bjwebb who opened the branch (I just created the PR).

**Comment by odscjames** [comment]
@Bjwebb Is this still relevant? There is some comments in the issue about where to solve this problem.

**Comment by BibianaC** [comment]
@Bjwebb can this PR be closed?

**Comment by duncandewhurst** [comment]
Closing per https://github.com/OpenDataServices/flatten-tool/issues/101#issuecomment-1758539667

**Pull request closed without merging**
