### PR TITLE
flatten: Use titles for sheet names

### PR DESCRIPTION
**Pull request by Bjwebb**
https://github.com/OpenDataServices/flatten-tool/issues/306

### CODE REVIEW

**Comment by odscjames** [comment]
Changelog :-)

**Review by odscjames — DISMISSED** [review]
I'm slightly puzzled why "examples/flatten/rollup/badschema/expected/cafe.csv " is seeing removing those columns as a change but if your happy with that that's ok.

**Comment by Bjwebb** [comment]
I'd discounted that as it said `badschema`, but looking at it again, I think there might be an issue with titles and rollup. I'll have a closer look.

**Comment by Bjwebb** [comment]
@odscjames I've added a fix so that rollup works correctly, and now none of the example files are changed (apart from renames).

**Review by odscjames — APPROVED** [review]

**Pull request merged**
