### PR TITLE
Rename fixture file to fix case sensitivity issue

### PR DESCRIPTION
**Pull request by andylolz**
Refs #195.

### CODE REVIEW

**Comment by andylolz** [comment]
Python 3.4 sporadically fails on travis. (I just force push to retest until it works!)

**Comment by Bjwebb** [comment]
This conflicts with the anonymise pull request that is now merged.

**Comment by andylolz** [comment]
Oh yeah, good point. Bear with me caller…

**Comment by andylolz** [comment]
Force pushed (because it was easier to redo than resolve conflicts).

**Comment by andylolz** [comment]
Thanks for merging this! (I can remove the disk partition now!)

**Pull request merged**
