### PR TITLE
Sort attributes if using lxml; prevent self-closing tags

### PR DESCRIPTION
**Pull request by andylolz**
This makes output a bit more consistent if lxml is used, by ensuring:

 * attributes are always sorted alphabetically
 * self-closing tags are never used

Refs #198.

### CODE REVIEW

**Comment by Bjwebb** [comment]
Hmmm, I don't like `method='html'`, because I'm not sure what undesirable effects it might have. I also prefer the look of self closing tags, but that's not so important.

**Comment by Bjwebb** [comment]
I'm doing some work on this in https://github.com/OpenDataServices/flatten-tool/compare/198-test-lxml
Sticking with `method='html'` for now, because I can't think of anything much better.

**Comment by Bjwebb** [comment]
I think the best alternative here would be to require lxml. I've avoiding doing this in the past, because lxml could be a pain to install, but these days we have linux wheels for all the main platforms. Requiring lxml would avoid doing `method=html` here, would allow us to keep self closing tags, and would make it easier to pretty print the output xml (https://github.com/OpenDataServices/flatten-tool/pull/189).

@andylolz What do you think?

**Comment by andylolz** [comment]
Closing in favour of #207.

**Pull request closed without merging**
