### PR TITLE
Accept input from standard input for flatten subcommand

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by odscjames** [comment]
This seems like a good idea and fine. 

However can we have an update in the https://github.com/OpenDataServices/flatten-tool/blob/master/CHANGELOG.md file, following the headings in https://keepachangelog.com/en/1.0.0/ ? 

Also a mention in the docs would be good, maybe just add to https://flatten-tool.readthedocs.io/en/latest/flatten/#generating-a-spreadsheet-from-a-json-document something like:

    You can also pass the JSON Document as standard input:

    $ cat examples/receipt/normalised/expected.json | flatten-tool flatten --root-list-path=cafe --main-sheet-name=cafe --schema=examples/receipt/cafe.schema  -o examples/flatten/simple/actual

A test could be added too - flatten/simple could be copied to flatten/commandline and the above command used instead. 

Hope that's ok - we're just trying to make sure the code remains workable for all devs in the future with a low barrier to entry, and that tests recheck functionality to lower the fear of changing stuff. I can pick all that up later if you want,

**Comment by jpmckinney** [comment]
Sounds good! For this and other PRs, I first wanted to get a nod on general direction before updating the changelog, docs and tests. Also, I don't know my way around the docs and tests yet, so tips (as above) on where to edit those are very helpful :)

**Comment by jpmckinney** [comment]
Hmm, I may have misunderstood your instruction regarding tests, but it doesn't look like flatten-tool has a test harness for simulating command-line interaction. I'll copy a pattern from ocdskit.

**Comment by jpmckinney** [comment]
I originally had a cute workaround taking advantage of `open` in Python 3 accepting file descriptors (i.e. sys.stdin.fileno() which is `0`), but both my test *and* pytest itself patch sys.stdin, such that this doesn't work – so I changed the implementation to be more direct.

**Comment by jpmckinney** [comment]
I'm a little stumped by the last error in Python 2.7.

```
            if output_name is None:
>               print(json.dumps(base, indent=4, default=decimal_default, ensure_ascii=False))
E               TypeError: unicode argument expected, got 'str'
```

**Comment by odscjames** [comment]
Just a quick note: in #267 there is a request to be able to pass a JSON object to this function, for API use. It seems like with one Pull Request we can add both the ability to accept a JSON Object and STD IN, if we had: 
 
>  json.load(sys.stdin.buffer, object_pairs_hook=OrderedDict, parse_float=Decimal)

in the CLI code and then passed the resulting JSON object to the function. What do you think? I'm happy to try this later?

**Comment by jpmckinney** [comment]
Sure, I'd be happy to either merge this first and make that change later, or do both at once. I'm in favor of #267, as ideally `flatten` (and `unflatten`, etc.) wouldn't interact with stdin/stdout or files at all, and instead leave that to whatever calls it.

**Comment by jpmckinney** [comment]
#267 was closed, and there's no activity on #269 at the moment. I'd be happy to fix conflicts if this PR can be merged. I don't see a need to do both this and #269 at once.

**Comment by robredpath** [comment]
[Make flatten-tool accept STDIN](https://trello.com/c/2Y5lglx7/41-make-flatten-tool-accept-stdin)

**Comment by odscjames** [comment]
@jpmckinney Is this still a priority? The Trello card is archived.

**Comment by jpmckinney** [comment]
No. For large files, stdin isn't an option anyway.

**Pull request closed without merging**
