### PR TITLE
Update copyright year to 2020

### PR DESCRIPTION
**Pull request by BibianaC**

### CODE REVIEW

**Comment by odscjames** [comment]
I'm not sure if it should be 2016-2020 or 2020?

**Comment by BibianaC** [comment]
@odscjames good point. I guess that 2016-2020 makes more sense?

**Comment by odscjames** [comment]
I think that makes more sense but I don't have any legal knowledge to back that up :-)

**Comment by BibianaC** [comment]
@odscjames done it.

**Pull request merged**
