### PR TITLE
.ods support

### PR DESCRIPTION
**Pull request by michaelwood**
Add basic Open Document Spreadsheet support to flatten tool

### CODE REVIEW

**Comment by Bjwebb** [comment]
I think we need some tests of this before we merge it.

These tests loop over the FORMATS array, but they need a step adding to check the generated ODS is as expected: https://github.com/OpenDataServices/flatten-tool/blob/mw/ods_support/flattentool/tests/test_output.py#L33
There's also a bunch of XLSX fixtures, it would be good to convert some of these to ODS and test them: https://github.com/OpenDataServices/flatten-tool/tree/mw/ods_support/flattentool/tests/fixtures/xlsx

**Comment by Bjwebb** [comment]
I've made a branch to add this to CoVE: https://github.com/OpenDataServices/cove/tree/flatten-tool-ods-support

Here's some dev deploys:
* IATI: http://flatten-tool-ods-support.dev.cove.opendataservices.coop/
* 360Giving: http://flatten-tool-ods-support.cove-360-dev.default.threesixtygiving.uk0.bigv.io/

Note that Meta tabs don't currently work, as the code for that hasn't been written yet.

**Comment by Bjwebb** [comment]
I've add Meta tab support.

**Comment by stevieflow** [comment]
I can't get the IATI one to work.  I saved the sample file as a .ods - but get

> Sorry, we can't process that data
> We think you tried to supply a spreadsheet, but we failed to convert it.
> 
> Error message: IndexError('list index out of range',)

[CoVE IATI 2.03 #minimal #activity #public #demo #2018-10-29.xlsx](https://github.com/OpenDataServices/flatten-tool/files/3951408/CoVE.IATI.2.03.minimal.activity.public.demo.2018-10-29.xlsx)

@KDuerden has been testing 360...

**Comment by KDuerden** [comment]
I've checked test data in ods format and it works: http://flatten-tool-ods-support.cove-360-dev.default.threesixtygiving.uk0.bigv.io/data/94028033-c675-448e-b7c1-c4d59823950c

I also tried with ods with meta tab but got an Index Error.
I can share the test files via planio if you need.

**Comment by Bjwebb** [comment]
Clearly the Meta tab support isn't working properly, so sorry about that. Thanks for sharing the test files, as this will make it easier to debug. I'm off tomorrow, but I'll take a look at this on Friday.

**Comment by Lathrisk** [comment]
The tests are now working again, with the exception of one new test which is pending a code fix.

**Comment by Bjwebb** [comment]
[Write tests for flatten-tool .ods support + merge + deploy to CoVEs](https://trello.com/c/qDgyY63Z/4-write-tests-for-flatten-tool-ods-support-merge-deploy-to-coves)

**Comment by Bjwebb** [comment]
@michaelwood Could you review my changes to this PR? https://github.com/OpenDataServices/flatten-tool/pull/326/files/249bf9eaa5caf387b9f66201c5e50b25c0593438..6bd62c4950d3838f66bbd5a9acab094e22e79e4a

**Comment by Bjwebb** [comment]
@stevieflow @KDuerden Meta tab support should now be fixed.

I've updated the dev deploys:
* IATI: http://flatten-tool-ods-support.dev.cove.opendataservices.coop/
* 360Giving: http://flatten-tool-ods-support.cove-360-dev.default.threesixtygiving.uk0.bigv.io/

**Comment by Bjwebb** [comment]
@michaelwood I've fixed the date issues you noticed. (And a bunch of other bugs I noticed).

I've updated the CoVE dev deploys:
* IATI: http://flatten-tool-ods-support.dev.cove.opendataservices.coop/
* 360Giving: http://flatten-tool-ods-support.cove-360-dev.default.threesixtygiving.uk0.bigv.io/

**Comment by Bjwebb** [comment]
I'm aware of some issues with certain 360Giving .ods files, and the "Last Modified" column not converting correctly (its treated as a `date` instead of a `date-time`). However, I think we should merge and deploy what we've got here, because:
1) I'm unlikely to get it fixed this week, and some .ods support is better than none.
2) Existing xlsx and csv files aren't affected
3) IATI support seems to work fine
4) There's a work around (modify the time e.g. add a second). Also, the column is optional.
5) My proposed fix changes some core bits of flatten-tool, so will need careful review to make sure other file formats aren't affected.

**Comment by KDuerden** [comment]
thanks for this update @Bjwebb 
Sounds sensible - no current or pipeline 360 publishers are using this file format yet, so there is no direct impact on users at the moment.

**Comment by Bjwebb** [comment]
This is now waiting for @michaelwood to review the changes I've made to the PR.

**Comment by michaelwood** [comment]
Superseded by pull #339

**Pull request closed without merging**
